apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: registry.k8s.io/e2e-test-images/echoserver:2.5
        name: echoserver
        ports:
        - containerPort: 8080
