apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    # The key part, matching ingress.annotations macro in cloudbees-core chart:
    alb.ingress.kubernetes.io/group.name: {{ include "fullname" .}}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: echoserver
                port:
                  number: 80
